# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b90744d313b59950260386ea9f2e15b70abff8fe882d56263e6ceedf13b63a8b2c4025dd17af64b1b5eaac1a1dee95c0d9111c52298362059b434fcf2c402f78

test:
  secret_key_base: 74c61678ac0a3db2913edc6e4cae9f2c07244d00a2eb37163f16b03b6134d5b5ba8d927d9e77818dfb97699aed832b74f143db9e081060910c9b5de8044c6107

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
